import { readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve, basename } from 'node:path';
import { pathToFileURL } from 'node:url';

export const assetDirectory = resolve('public/assets/models/fighters/trellis2');
export const catalogPath = resolve('src/features/characters/trellis2.generated.ts');

/**
 * Verify enough of the GLB 2.0 container to avoid advertising broken assets.
 * This is deliberately not a full mesh or animation validator.
 */
export function validateGlb(buffer, filename) {
  if (buffer.length < 28 || buffer.readUInt32LE(0) !== 0x46546c67 ||
      buffer.readUInt32LE(4) !== 2 || buffer.readUInt32LE(8) !== buffer.length) {
    throw new Error(`${filename}: invalid GLB header or length`);
  }
  const length = buffer.readUInt32LE(12);
  if (buffer.readUInt32LE(16) !== 0x4e4f534a || 20 + length > buffer.length) {
    throw new Error(`${filename}: missing GLB JSON chunk`);
  }
  let json;
  try {
    json = JSON.parse(buffer.subarray(20, 20 + length).toString('utf8').trim());
  } catch {
    throw new Error(`${filename}: malformed GLB JSON`);
  }
  if (json.asset?.version !== '2.0' || !Array.isArray(json.meshes) || !json.meshes.length) {
    throw new Error(`${filename}: expected glTF 2.0 with at least one mesh`);
  }
  return true;
}

export function createCatalog(ids) {
  const entries = ids.sort().map((id) =>
    `  ${JSON.stringify(id)}: ${JSON.stringify(`/assets/models/fighters/trellis2/${id}.glb`)}`
  );
  return [
    '/** Generated by scripts/trellis2/sync-assets.mjs. Do not edit manually. */',
    'export const TRELLIS_CHARACTER_ASSETS: Readonly<Record<string, string>> = {',
    entries.join(',\n'),
    '};',
    ''
  ].join('\n');
}

export async function syncAssets({ directory = assetDirectory, output = catalogPath, check = false } = {}) {
  let names = [];
  try {
    names = await readdir(directory);
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
  const ids = [];
  for (const name of names) {
    if (!name.endsWith('.glb')) continue;
    const id = basename(name, '.glb');
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id)) {
      throw new Error(`Invalid TRELLIS.2 character ID in filename: ${name}`);
    }
    validateGlb(await readFile(resolve(directory, name)), name);
    ids.push(id);
  }
  const source = createCatalog(ids);
  if (check) {
    if ((await readFile(output, 'utf8')) !== source) {
      throw new Error('TRELLIS.2 catalog is out of sync; run npm run sync:trellis');
    }
  } else {
    await writeFile(output, source);
  }
  return ids;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  syncAssets({ check: process.argv.includes('--check') })
    .then((ids) => console.log(`TRELLIS.2: registered ${ids.length} generated character GLB(s).`))
    .catch((error) => {
      console.error(error.message);
      process.exitCode = 1;
    });
}
