/**
 * Extended NINJAGO character planning catalog.
 *
 * This is intentionally separate from the live ROSTER in roster.ts.
 * Entries here are staged candidates and do not automatically become playable.
 * Names/powers come from the project owner's supplied roster notes.
 * Wave numbers and asset strategy are implementation planning decisions.
 */
export type RosterImplementationWave = 1 | 2 | 3 | 4;

export interface ExpandedCharacterCatalogEntry {
  id: string;
  name: string;
  power: string;
  era: string;
  group: string;
  wave: RosterImplementationWave;
}

export const REQUIRED_CHARACTER_ASSETS = ['portrait', 'svg-icon', 'procedural-3d'] as const;

export const EXPANDED_CHARACTER_CATALOG: readonly ExpandedCharacterCatalogEntry[] = [
  { id: "kai", name: "Kai", power: "🔥 Fire", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "jay-walker", name: "Jay Walker", power: "⚡ Lightning", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "cole", name: "Cole", power: "🪨 Earth", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "zane", name: "Zane", power: "❄️ Ice", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "nya", name: "Nya", power: "💧 Water", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "lloyd-garmadon", name: "Lloyd Garmadon", power: "💚 Energy / Life / formerly Golden Power", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "master-wu", name: "Master Wu", power: "✨ Creation + Spinjitzu", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "lord-garmadon", name: "Lord Garmadon", power: "💥 Destruction + Oni Power", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "pixal", name: "P.I.X.A.L.", power: "🤖 Nindroid abilities / Technology", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "skylor", name: "Skylor", power: "🟠 Amber: copies/absorbs other Elemental Powers", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "arin", name: "Arin", power: "🌀 Spinjitzu / Object Spinjitzu; no Elemental Power", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "sora", name: "Sora", power: "💻 Technology", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "wyldfyre", name: "Wyldfyre", power: "♨️ Heat", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "frak", name: "Frak", power: "🌋 Quake", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "euphrasia", name: "Euphrasia", power: "🌪️ Wind", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "geo", name: "Geo", power: "🔗 Fusion", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "riyu", name: "Riyu", power: "🐉 Dragon Energy", era: "Core / Elemental roster", group: "Original Ninja / Main heroes", wave: 1 },
  { id: "karlof", name: "Karlof", power: "⚙️ Metal", era: "Core / Elemental roster", group: "Original Elemental Masters", wave: 1 },
  { id: "griffin-turner", name: "Griffin Turner", power: "💨 Speed", era: "Core / Elemental roster", group: "Original Elemental Masters", wave: 1 },
  { id: "shade", name: "Shade", power: "🌑 Shadow", era: "Core / Elemental roster", group: "Original Elemental Masters", wave: 1 },
  { id: "neuro", name: "Neuro", power: "🧠 Mind", era: "Core / Elemental roster", group: "Original Elemental Masters", wave: 1 },
  { id: "mr-pale-paleman", name: "Mr. Pale / Paleman", power: "💡 Light / Invisibility", era: "Core / Elemental roster", group: "Original Elemental Masters", wave: 1 },
  { id: "tox", name: "Tox", power: "☠️ Poison", era: "Core / Elemental roster", group: "Original Elemental Masters", wave: 1 },
  { id: "jacob-pevsner", name: "Jacob Pevsner", power: "🔊 Sound", era: "Core / Elemental roster", group: "Original Elemental Masters", wave: 1 },
  { id: "bolobo", name: "Bolobo", power: "🌿 Nature", era: "Core / Elemental roster", group: "Original Elemental Masters", wave: 1 },
  { id: "chamille", name: "Chamille", power: "🦎 Form / Shapeshifting", era: "Core / Elemental roster", group: "Original Elemental Masters", wave: 1 },
  { id: "ash", name: "Ash", power: "🌫️ Smoke", era: "Core / Elemental roster", group: "Original Elemental Masters", wave: 1 },
  { id: "gravis", name: "Gravis", power: "🪐 Gravity", era: "Core / Elemental roster", group: "Original Elemental Masters", wave: 1 },
  { id: "skylor-2", name: "Skylor", power: "🟠 Amber / Power copying", era: "Core / Elemental roster", group: "Original Elemental Masters", wave: 1 },
  { id: "frak-2", name: "Frak", power: "🌋 Quake", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "cinder", name: "Cinder", power: "🌫️ Smoke", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "obscuria", name: "Obscuria", power: "🌑 Shadow", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "kizzy", name: "Kizzy", power: "⚖️ Balance", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "zur", name: "Zur", power: "⚡ Reflex", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "zant-tanz", name: "Zant-Tanz", power: "🌱 Plants", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "geo-2", name: "Geo", power: "🔗 Fusion", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "zeatrix", name: "Zeatrix", power: "💥 Shockwave", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "gorge", name: "Gorge", power: "📏 Size", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "mord", name: "Mord", power: "💧 Surface Tension", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "algu", name: "Algu", power: "🎭 Figment / Illusions", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "teelk", name: "Teelk", power: "🔊 Sound", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "arccrack", name: "Arccrack", power: "🚀 Propulsion", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "euphrasia-2", name: "Euphrasia", power: "🌪️ Wind", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "sora-2", name: "Sora", power: "💻 Technology", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "wyldfyre-2", name: "Wyldfyre", power: "♨️ Heat", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "lloyd", name: "Lloyd", power: "💚 Energy / Life", era: "Core / Elemental roster", group: "New Elemental Masters — Dragons Rising", wave: 4 },
  { id: "samukai", name: "Samukai", power: "💀 Skulkin strength + four-arm combat", era: "Pilots / Skeleton Army", group: "Pilots / Skeleton Army", wave: 2 },
  { id: "kruncha", name: "Kruncha", power: "💀 Super strength / axe combat", era: "Pilots / Skeleton Army", group: "Pilots / Skeleton Army", wave: 2 },
  { id: "nuckal", name: "Nuckal", power: "💀 Skulkin combat", era: "Pilots / Skeleton Army", group: "Pilots / Skeleton Army", wave: 2 },
  { id: "wyplash", name: "Wyplash", power: "💀 Weapons / stealth", era: "Pilots / Skeleton Army", group: "Pilots / Skeleton Army", wave: 2 },
  { id: "frakjaw", name: "Frakjaw", power: "💀 Skulkin combat", era: "Pilots / Skeleton Army", group: "Pilots / Skeleton Army", wave: 2 },
  { id: "chopov", name: "Chopov", power: "💀 Skulkin combat", era: "Pilots / Skeleton Army", group: "Pilots / Skeleton Army", wave: 2 },
  { id: "krazi", name: "Krazi", power: "💀 Skulkin combat", era: "Pilots / Skeleton Army", group: "Pilots / Skeleton Army", wave: 2 },
  { id: "bonezai", name: "Bonezai", power: "💀 Skulkin combat", era: "Pilots / Skeleton Army", group: "Pilots / Skeleton Army", wave: 2 },
  { id: "flame", name: "Flame", power: "🔥 Fire", era: "Pilots / Skeleton Army", group: "Original Dragons", wave: 2 },
  { id: "wisp", name: "Wisp", power: "⚡ Lightning", era: "Pilots / Skeleton Army", group: "Original Dragons", wave: 2 },
  { id: "rocky", name: "Rocky", power: "🪨 Earth", era: "Pilots / Skeleton Army", group: "Original Dragons", wave: 2 },
  { id: "shard", name: "Shard", power: "❄️ Ice", era: "Pilots / Skeleton Army", group: "Original Dragons", wave: 2 },
  { id: "ultra-dragon", name: "Ultra Dragon", power: "🔥⚡🪨❄️ Fire + Lightning + Earth + Ice", era: "Pilots / Skeleton Army", group: "Original Dragons", wave: 2 },
  { id: "pythor-p-chumsworth", name: "Pythor P. Chumsworth", power: "🐍 Anacondrai powers / invisibility / enhanced strength", era: "Rise of the Snakes", group: "Anacondrai", wave: 2 },
  { id: "general-arcturus", name: "General Arcturus", power: "🐍 Anacondrai abilities", era: "Rise of the Snakes", group: "Anacondrai", wave: 2 },
  { id: "skales", name: "Skales", power: "👁️ Hypnosis", era: "Rise of the Snakes", group: "Hypnobrai", wave: 2 },
  { id: "slithraa", name: "Slithraa", power: "👁️ Hypnosis", era: "Rise of the Snakes", group: "Hypnobrai", wave: 2 },
  { id: "mezmo", name: "Mezmo", power: "👁️ Hypnosis", era: "Rise of the Snakes", group: "Hypnobrai", wave: 2 },
  { id: "rattla", name: "Rattla", power: "👁️ Hypnosis", era: "Rise of the Snakes", group: "Hypnobrai", wave: 2 },
  { id: "selma", name: "Selma", power: "👁️ Hypnobrai abilities", era: "Rise of the Snakes", group: "Hypnobrai", wave: 2 },
  { id: "skales-jr", name: "Skales Jr.", power: "👁️ Hypnobrai abilities", era: "Rise of the Snakes", group: "Hypnobrai", wave: 2 },
  { id: "fangtom", name: "Fangtom", power: "🐍 Transforming venom/bite", era: "Rise of the Snakes", group: "Fangpyre", wave: 2 },
  { id: "fangdam", name: "Fangdam", power: "🐍 Transforming venom", era: "Rise of the Snakes", group: "Fangpyre", wave: 2 },
  { id: "fang-suei", name: "Fang-Suei", power: "🐍 Transforming venom", era: "Rise of the Snakes", group: "Fangpyre", wave: 2 },
  { id: "snappa", name: "Snappa", power: "🐍 Transforming venom", era: "Rise of the Snakes", group: "Fangpyre", wave: 2 },
  { id: "skalidor", name: "Skalidor", power: "💪 Super strength / constriction", era: "Rise of the Snakes", group: "Constrictai", wave: 2 },
  { id: "bytar", name: "Bytar", power: "💪 Super strength", era: "Rise of the Snakes", group: "Constrictai", wave: 2 },
  { id: "chokun", name: "Chokun", power: "💪 Super strength", era: "Rise of the Snakes", group: "Constrictai", wave: 2 },
  { id: "snike", name: "Snike", power: "💪 Constrictai strength", era: "Rise of the Snakes", group: "Constrictai", wave: 2 },
  { id: "acidicus", name: "Acidicus", power: "☣️ Hallucinogenic venom", era: "Rise of the Snakes", group: "Venomari", wave: 2 },
  { id: "lizaru", name: "Lizaru", power: "☣️ Venom", era: "Rise of the Snakes", group: "Venomari", wave: 2 },
  { id: "spitta", name: "Spitta", power: "☣️ Venom", era: "Rise of the Snakes", group: "Venomari", wave: 2 },
  { id: "lasha", name: "Lasha", power: "☣️ Venom", era: "Rise of the Snakes", group: "Venomari", wave: 2 },
  { id: "great-devourer", name: "Great Devourer", power: "🐍 Massive strength + venom + continual growth", era: "Rise of the Snakes", group: "Venomari", wave: 2 },
  { id: "mystake", name: "Mystake", power: "👹 Oni transformation / shapeshifting", era: "Rise of the Snakes", group: "Venomari", wave: 2 },
  { id: "ed-walker", name: "Ed Walker", power: "🔧 Inventor/mechanic; no element", era: "Rise of the Snakes", group: "Venomari", wave: 2 },
  { id: "edna-walker", name: "Edna Walker", power: "🛠️ Mechanic; no element", era: "Rise of the Snakes", group: "Venomari", wave: 2 },
  { id: "first-spinjitzu-master", name: "First Spinjitzu Master", power: "🌟 Creation / Golden Power / ancient elemental power", era: "Legacy of the Green Ninja", group: "Legacy of the Green Ninja", wave: 2 },
  { id: "the-overlord", name: "The Overlord", power: "🌑 Darkness", era: "Legacy of the Green Ninja", group: "Legacy of the Green Ninja", wave: 2 },
  { id: "general-kozu", name: "General Kozu", power: "🗿 Stone Warrior super strength", era: "Legacy of the Green Ninja", group: "Legacy of the Green Ninja", wave: 2 },
  { id: "dareth", name: "Dareth", power: "🟤 Martial arts / “Brown Ninja”; no element", era: "Legacy of the Green Ninja", group: "Legacy of the Green Ninja", wave: 2 },
  { id: "lou", name: "Lou", power: "🎵 No Elemental Power", era: "Legacy of the Green Ninja", group: "Legacy of the Green Ninja", wave: 2 },
  { id: "dr-julien", name: "Dr. Julien", power: "🧠 Engineering / robotics", era: "Legacy of the Green Ninja", group: "Legacy of the Green Ninja", wave: 2 },
  { id: "captain-soto", name: "Captain Soto", power: "⚔️ Swordsmanship / pirate combat", era: "Legacy of the Green Ninja", group: "Legacy of the Green Ninja", wave: 2 },
  { id: "no-eyed-pete", name: "No-Eyed Pete", power: "⚔️ Pirate combat", era: "Legacy of the Green Ninja", group: "Legacy of the Green Ninja", wave: 2 },
  { id: "bizarro-kai", name: "Bizarro Kai", power: "🔥 Dark copy of Kai", era: "Legacy of the Green Ninja", group: "Bizarro Ninja", wave: 2 },
  { id: "bizarro-jay", name: "Bizarro Jay", power: "⚡ Dark copy of Jay", era: "Legacy of the Green Ninja", group: "Bizarro Ninja", wave: 2 },
  { id: "bizarro-cole", name: "Bizarro Cole", power: "🪨 Dark copy of Cole", era: "Legacy of the Green Ninja", group: "Bizarro Ninja", wave: 2 },
  { id: "bizarro-zane", name: "Bizarro Zane", power: "❄️ Dark copy of Zane", era: "Legacy of the Green Ninja", group: "Bizarro Ninja", wave: 2 },
  { id: "cyrus-borg", name: "Cyrus Borg", power: "💻 Technology / genius inventor", era: "Rebooted", group: "Rebooted", wave: 2 },
  { id: "pixal-2", name: "P.I.X.A.L.", power: "🤖 Nindroid abilities", era: "Rebooted", group: "Rebooted", wave: 2 },
  { id: "general-cryptor", name: "General Cryptor", power: "🤖 Nindroid strength / weapons", era: "Rebooted", group: "Rebooted", wave: 2 },
  { id: "min-droid", name: "Min-Droid", power: "🤖 Nindroid abilities", era: "Rebooted", group: "Rebooted", wave: 2 },
  { id: "digital-overlord", name: "Digital Overlord", power: "🌑 Darkness / digital control", era: "Rebooted", group: "Rebooted", wave: 2 },
  { id: "golden-master", name: "Golden Master", power: "🌑 Darkness + amplified Golden Power", era: "Rebooted", group: "Rebooted", wave: 2 },
  { id: "nindroid-army", name: "Nindroid Army", power: "🤖 Robotic combat", era: "Rebooted", group: "Rebooted", wave: 2 },
  { id: "nindroid-mechdragon", name: "Nindroid MechDragon", power: "🤖🐉 Mechanical dragon weapons", era: "Rebooted", group: "Rebooted", wave: 2 },
  { id: "master-chen", name: "Master Chen", power: "🪄 Staff of Elements / steals Elemental Powers", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "clouse", name: "Clouse", power: "🔮 Dark Magic", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "eyezor", name: "Eyezor", power: "⚔️ Anacondrai cult warrior", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "zugu", name: "Zugu", power: "💪 Strength", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "kapau", name: "Kapau", power: "⚔️ Combat", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "chope", name: "Chope", power: "⚔️ Combat", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "krait", name: "Krait", power: "🐍 Anacondrai transformation", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "sleven", name: "Sleven", power: "🐍 Anacondrai transformation", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "skylor-3", name: "Skylor", power: "🟠 Amber", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "karlof-2", name: "Karlof", power: "⚙️ Metal", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "griffin-turner-2", name: "Griffin Turner", power: "💨 Speed", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "shade-2", name: "Shade", power: "🌑 Shadow", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "neuro-2", name: "Neuro", power: "🧠 Mind", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "mr-pale", name: "Mr. Pale", power: "💡 Light", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "tox-2", name: "Tox", power: "☠️ Poison", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "jacob", name: "Jacob", power: "🔊 Sound", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "bolobo-2", name: "Bolobo", power: "🌿 Nature", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "chamille-2", name: "Chamille", power: "🦎 Form", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "ash-2", name: "Ash", power: "🌫️ Smoke", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "gravis-2", name: "Gravis", power: "🪐 Gravity", era: "Tournament of Elements", group: "Tournament of Elements", wave: 1 },
  { id: "morro", name: "Morro", power: "🌪️ Wind + Ghost powers", era: "Possession", group: "Possession", wave: 2 },
  { id: "bansha", name: "Bansha", power: "👻 Ghost powers / powerful scream", era: "Possession", group: "Possession", wave: 2 },
  { id: "soul-archer", name: "Soul Archer", power: "👻🏹 Ghost archery", era: "Possession", group: "Possession", wave: 2 },
  { id: "wrayth", name: "Wrayth", power: "👻 Ghost abilities", era: "Possession", group: "Possession", wave: 2 },
  { id: "ghoultar", name: "Ghoultar", power: "👻 Super strength", era: "Possession", group: "Possession", wave: 2 },
  { id: "master-yang", name: "Master Yang", power: "🌀 Airjitzu + Ghost powers", era: "Possession", group: "Possession", wave: 2 },
  { id: "the-preeminent", name: "The Preeminent", power: "👻 Cursed Realm entity / controls ghosts", era: "Possession", group: "Possession", wave: 2 },
  { id: "ronin", name: "Ronin", power: "🔫 Weapons / technology / mercenary skills", era: "Possession", group: "Possession", wave: 2 },
  { id: "fenwick", name: "Fenwick", power: "🪽 Realm guardian abilities", era: "Possession", group: "Possession", wave: 2 },
  { id: "nimbus", name: "Nimbus", power: "☁️ Cloud creature", era: "Possession", group: "Possession", wave: 2 },
  { id: "nadakhan", name: "Nadakhan", power: "🧞 Wish Magic / teleportation / Djinn powers", era: "Skybound", group: "Skybound", wave: 2 },
  { id: "flintlocke", name: "Flintlocke", power: "🎯 Superhuman-level marksmanship", era: "Skybound", group: "Skybound", wave: 2 },
  { id: "dogshank", name: "Dogshank", power: "💪 Extreme strength", era: "Skybound", group: "Skybound", wave: 2 },
  { id: "doubloon", name: "Doubloon", power: "🌀 Spinjitzu + martial arts", era: "Skybound", group: "Skybound", wave: 2 },
  { id: "monkey-wretch", name: "Monkey Wretch", power: "🤖 Mechanical/cyborg abilities", era: "Skybound", group: "Skybound", wave: 2 },
  { id: "clancee", name: "Clancee", power: "🐍 Serpentine abilities", era: "Skybound", group: "Skybound", wave: 2 },
  { id: "squiffy", name: "Squiffy", power: "⚔️ Pirate combat", era: "Skybound", group: "Skybound", wave: 2 },
  { id: "bucko", name: "Bucko", power: "⚔️ Pirate combat", era: "Skybound", group: "Skybound", wave: 2 },
  { id: "cyren", name: "Cyren", power: "⚔️ Pirate combat", era: "Skybound", group: "Skybound", wave: 2 },
  { id: "khanjikhan", name: "Khanjikhan", power: "🧞 Djinn magic", era: "Skybound", group: "Skybound", wave: 2 },
  { id: "the-mechanic", name: "The Mechanic", power: "⚙️ Technology / mechanical weapons", era: "Skybound", group: "Skybound", wave: 2 },
  { id: "nelson", name: "Nelson", power: "🟣 Ninja training / martial arts", era: "Skybound", group: "Skybound", wave: 2 },
  { id: "krux", name: "Krux", power: "⏳ Time", era: "Hands of Time", group: "Hands of Time", wave: 3 },
  { id: "acronix", name: "Acronix", power: "⏳ Time", era: "Hands of Time", group: "Hands of Time", wave: 3 },
  { id: "ray", name: "Ray", power: "🔥 Fire — former Elemental Master", era: "Hands of Time", group: "Hands of Time", wave: 3 },
  { id: "maya", name: "Maya", power: "💧 Water — former Elemental Master", era: "Hands of Time", group: "Hands of Time", wave: 3 },
  { id: "machia", name: "Machia", power: "🐍 Vermillion hive control", era: "Hands of Time", group: "Hands of Time", wave: 3 },
  { id: "raggmunk", name: "Raggmunk", power: "🐍 Vermillion abilities", era: "Hands of Time", group: "Hands of Time", wave: 3 },
  { id: "blunck", name: "Blunck", power: "🐍 Vermillion abilities", era: "Hands of Time", group: "Hands of Time", wave: 3 },
  { id: "slackjaw", name: "Slackjaw", power: "🐍 Vermillion abilities", era: "Hands of Time", group: "Hands of Time", wave: 3 },
  { id: "rivett", name: "Rivett", power: "🐍 Vermillion abilities", era: "Hands of Time", group: "Hands of Time", wave: 3 },
  { id: "tannin", name: "Tannin", power: "🐍 Vermillion abilities", era: "Hands of Time", group: "Hands of Time", wave: 3 },
  { id: "harumi", name: "Harumi", power: "⚔️ Martial arts / strategy; no element", era: "Sons of Garmadon", group: "Sons of Garmadon", wave: 3 },
  { id: "killow", name: "Killow", power: "💪 Extreme strength + Oni Mask", era: "Sons of Garmadon", group: "Sons of Garmadon", wave: 3 },
  { id: "ultra-violet", name: "Ultra Violet", power: "🗡️ Acrobatics/combat + Oni Mask", era: "Sons of Garmadon", group: "Sons of Garmadon", wave: 3 },
  { id: "mr-e", name: "Mr. E", power: "🤖 Nindroid strength + Oni Mask", era: "Sons of Garmadon", group: "Sons of Garmadon", wave: 3 },
  { id: "luke-cunningham", name: "Luke Cunningham", power: "🥋 Combat", era: "Sons of Garmadon", group: "Sons of Garmadon", wave: 3 },
  { id: "hutchins", name: "Hutchins", power: "⚔️ Royal guard combat", era: "Sons of Garmadon", group: "Sons of Garmadon", wave: 3 },
  { id: "emperor-garmadon", name: "Emperor Garmadon", power: "💥 Destruction + Oni Power", era: "Sons of Garmadon", group: "Sons of Garmadon", wave: 3 },
  { id: "iron-baron", name: "Iron Baron", power: "🏹 Dragon-hunting weapons / no element", era: "Hunted", group: "Hunted", wave: 3 },
  { id: "faith-heavy-metal", name: "Faith / Heavy Metal", power: "🐉 Dragon riding + combat", era: "Hunted", group: "Hunted", wave: 3 },
  { id: "daddy-no-legs", name: "Daddy No Legs", power: "⚔️ Dragon Hunter combat", era: "Hunted", group: "Hunted", wave: 3 },
  { id: "muzzle", name: "Muzzle", power: "⚔️ Dragon Hunter combat", era: "Hunted", group: "Hunted", wave: 3 },
  { id: "jet-jack", name: "Jet Jack", power: "🚀 Jetpack combat", era: "Hunted", group: "Hunted", wave: 3 },
  { id: "chew-toy", name: "Chew Toy", power: "⚔️ Dragon Hunter", era: "Hunted", group: "Hunted", wave: 3 },
  { id: "firstbourne", name: "Firstbourne", power: "🐉 Primordial dragon power / multiple elemental affinities", era: "Hunted", group: "Dragons", wave: 3 },
  { id: "stormbringer", name: "Stormbringer", power: "⚡ Lightning", era: "Hunted", group: "Dragons", wave: 3 },
  { id: "slab", name: "Slab", power: "🐉 Dragon strength", era: "Hunted", group: "Dragons", wave: 3 },
  { id: "baby-stormbringer", name: "Baby Stormbringer", power: "⚡ Lightning/dragon abilities", era: "Hunted", group: "Dragons", wave: 3 },
  { id: "the-omega", name: "The Omega", power: "🌑 Oni Darkness / destruction", era: "March of the Oni", group: "March of the Oni", wave: 3 },
  { id: "oni-warlords", name: "Oni Warlords", power: "🌑 Oni powers / shapeshifting", era: "March of the Oni", group: "March of the Oni", wave: 3 },
  { id: "oni-army", name: "Oni Army", power: "🌑 Darkness / corruption / Oni physiology", era: "March of the Oni", group: "March of the Oni", wave: 3 },
  { id: "garmadon", name: "Garmadon", power: "💥 Destruction + Oni power", era: "March of the Oni", group: "March of the Oni", wave: 3 },
  { id: "aspheera", name: "Aspheera", power: "🐍🔮 Serpentine Sorcery + Spinjitzu + stolen Fire", era: "Secrets of the Forbidden Spinjitzu", group: "Fire Chapter", wave: 3 },
  { id: "char", name: "Char", power: "🔥 Pyro Viper abilities", era: "Secrets of the Forbidden Spinjitzu", group: "Fire Chapter", wave: 3 },
  { id: "king-mambo-v", name: "King Mambo V", power: "🐍 Serpentine abilities", era: "Secrets of the Forbidden Spinjitzu", group: "Fire Chapter", wave: 3 },
  { id: "pyro-vipers", name: "Pyro Vipers", power: "🔥 Fire-enhanced undead Serpentine", era: "Secrets of the Forbidden Spinjitzu", group: "Fire Chapter", wave: 3 },
  { id: "clutch-powers", name: "Clutch Powers", power: "🧭 Adventurer / relic expertise", era: "Secrets of the Forbidden Spinjitzu", group: "Fire Chapter", wave: 3 },
  { id: "fugi-dove", name: "Fugi-Dove", power: "🕊️ Aerial gadgets / criminal combat", era: "Secrets of the Forbidden Spinjitzu", group: "Fire Chapter", wave: 3 },
  { id: "miss-demeanor", name: "Miss Demeanor", power: "🔥 Weapons / explosives", era: "Secrets of the Forbidden Spinjitzu", group: "Fire Chapter", wave: 3 },
  { id: "ice-emperor-zane", name: "Ice Emperor / Zane", power: "❄️ Ice", era: "Secrets of the Forbidden Spinjitzu", group: "Ice Chapter", wave: 3 },
  { id: "general-vex", name: "General Vex", power: "🧠 Manipulation / strategy; no element", era: "Secrets of the Forbidden Spinjitzu", group: "Ice Chapter", wave: 3 },
  { id: "grimfax", name: "Grimfax", power: "⚔️ Blizzard Samurai combat", era: "Secrets of the Forbidden Spinjitzu", group: "Ice Chapter", wave: 3 },
  { id: "akita", name: "Akita", power: "🐺 Wolf shapeshifting", era: "Secrets of the Forbidden Spinjitzu", group: "Ice Chapter", wave: 3 },
  { id: "kataru", name: "Kataru", power: "🐻 Bear shapeshifting", era: "Secrets of the Forbidden Spinjitzu", group: "Ice Chapter", wave: 3 },
  { id: "sorla", name: "Sorla", power: "🔮 Wisdom / Never-Realm knowledge", era: "Secrets of the Forbidden Spinjitzu", group: "Ice Chapter", wave: 3 },
  { id: "krag", name: "Krag", power: "💪 Yeti strength", era: "Secrets of the Forbidden Spinjitzu", group: "Ice Chapter", wave: 3 },
  { id: "boreal", name: "Boreal", power: "❄️🐉 Ice", era: "Secrets of the Forbidden Spinjitzu", group: "Ice Chapter", wave: 3 },
  { id: "unagami", name: "Unagami", power: "🎮 Digital reality manipulation", era: "Prime Empire", group: "Prime Empire", wave: 3 },
  { id: "milton-dyer", name: "Milton Dyer", power: "💻 Programmer / inventor", era: "Prime Empire", group: "Prime Empire", wave: 3 },
  { id: "scott", name: "Scott", power: "🎮 Gaming / tech", era: "Prime Empire", group: "Prime Empire", wave: 3 },
  { id: "okino", name: "Okino", power: "⚔️ Swordsmanship", era: "Prime Empire", group: "Prime Empire", wave: 3 },
  { id: "racer-seven", name: "Racer Seven", power: "🏎️ Racing / speed", era: "Prime Empire", group: "Prime Empire", wave: 3 },
  { id: "sushimi", name: "Sushimi", power: "🍣⚔️ Digital combat", era: "Prime Empire", group: "Prime Empire", wave: 3 },
  { id: "richie", name: "Richie", power: "🤖 Digital warrior", era: "Prime Empire", group: "Prime Empire", wave: 3 },
  { id: "targle", name: "Targle", power: "🤖 Digital warrior", era: "Prime Empire", group: "Prime Empire", wave: 3 },
  { id: "red-visors", name: "Red Visors", power: "🤖 Enhanced digital soldiers", era: "Prime Empire", group: "Prime Empire", wave: 3 },
  { id: "avatar-harumi", name: "Avatar Harumi", power: "🎮 Digital avatar abilities", era: "Prime Empire", group: "Prime Empire", wave: 3 },
  { id: "king-vangelis-skull-sorcerer", name: "King Vangelis / Skull Sorcerer", power: "💀 Dark Skull Magic", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "princess-vania", name: "Princess Vania", power: "⚔️ Combat / no element", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "hailmar", name: "Hailmar", power: "⚔️ Warrior", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "hazza-d-ur", name: "Hazza D'Ur", power: "💀 Necromantic Skull Magic", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "murtessa", name: "Murtessa", power: "💪 Munce strength", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "murt", name: "Murt", power: "💪 Munce strength", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "gulch", name: "Gulch", power: "⛏️ Geckle combat", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "gleck", name: "Gleck", power: "⛏️ Geckle abilities", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "fungus", name: "Fungus", power: "🔮 Magic / spells", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "korgran", name: "Korgran", power: "🪓 Super strength", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "plundar", name: "Plundar", power: "🎲 Adventurer / enchanted dice", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "adam", name: "Adam", power: "🕷️ Giant spider abilities", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "grief-bringer", name: "Grief-Bringer", power: "💀🐉 Undead dragon power", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "chompy", name: "Chompy", power: "🔥🐉 Dragon abilities / fire", era: "Master of the Mountain", group: "Master of the Mountain", wave: 3 },
  { id: "chief-mammatus", name: "Chief Mammatus", power: "🗿 Keeper knowledge / combat", era: "The Island", group: "The Island", wave: 3 },
  { id: "twitchy-tim", name: "Twitchy Tim", power: "🧭 Explorer / survival", era: "The Island", group: "The Island", wave: 3 },
  { id: "ronin-2", name: "Ronin", power: "🔫 Technology / tricks", era: "The Island", group: "The Island", wave: 3 },
  { id: "poulerik", name: "PoulErik", power: "⚔️ Mercenary combat", era: "The Island", group: "The Island", wave: 3 },
  { id: "keepers", name: "Keepers", power: "⚡ Amulet/tribal weapons", era: "The Island", group: "The Island", wave: 3 },
  { id: "zippy", name: "Zippy", power: "🐉 Dragon flight / fire", era: "The Island", group: "The Island", wave: 3 },
  { id: "prince-kalmaar", name: "Prince Kalmaar", power: "🔱 Merlopian combat / trident / sea technology", era: "Seabound", group: "Seabound", wave: 3 },
  { id: "king-trimaar", name: "King Trimaar", power: "🔱 Merlopian abilities", era: "Seabound", group: "Seabound", wave: 3 },
  { id: "benthomaar", name: "Benthomaar", power: "🌊 Aquatic physiology + combat", era: "Seabound", group: "Seabound", wave: 3 },
  { id: "gripe", name: "Gripe", power: "🐙 Merlopian strength", era: "Seabound", group: "Seabound", wave: 3 },
  { id: "glutinous", name: "Glutinous", power: "🧪 Science / engineering", era: "Seabound", group: "Seabound", wave: 3 },
  { id: "nyad", name: "Nyad", power: "💧 Water", era: "Seabound", group: "Seabound", wave: 3 },
  { id: "wojira", name: "Wojira", power: "🌊🌪️ Wave + Storm / Water + Wind-like powers", era: "Seabound", group: "Seabound", wave: 3 },
  { id: "overlord-crystal-king", name: "Overlord / Crystal King", power: "🌑 Darkness / Crystal corruption", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "harumi-2", name: "Harumi", power: "⚔️ Combat / Crystal empowerment", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "mister-f", name: "Mister F", power: "🤖 Nindroid abilities", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "aspheera-2", name: "Aspheera", power: "🔮 Serpentine Magic", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "pythor", name: "Pythor", power: "🐍 Anacondrai abilities", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "vangelis", name: "Vangelis", power: "💀 Skull Magic", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "mechanic", name: "Mechanic", power: "⚙️ Technology", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "hounddog-mcbrag", name: "Hounddog McBrag", power: "🔫 Police combat", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "fugi-dove-2", name: "Fugi-Dove", power: "🕊️ Gadgets", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "ronin-3", name: "Ronin", power: "🔫 Technology/weapons", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "skylor-4", name: "Skylor", power: "🟠 Amber", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "nelson-2", name: "Nelson", power: "🟣 Ninja training", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "dareth-2", name: "Dareth", power: "🟤 Martial arts", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "cyrus-borg-2", name: "Cyrus Borg", power: "💻 Technology", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "twitchy-tim-2", name: "Twitchy Tim", power: "🧭 Survival/exploration", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "antonia", name: "Antonia", power: "🥋 Combat", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "jake", name: "Jake", power: "No Elemental Power", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "vinny-folson", name: "Vinny Folson", power: "No Elemental Power", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "sally", name: "Sally", power: "🎸 No Elemental Power", era: "Crystalized", group: "Crystalized", wave: 3 },
  { id: "empress-beatrix", name: "Empress Beatrix", power: "🤖 Imperium technology / mech weapons", era: "Dragons Rising — Imperium", group: "Dragons Rising — Imperium", wave: 4 },
  { id: "lord-ras", name: "Lord Ras", power: "🐯💥 Enhanced strength + Shatterspin", era: "Dragons Rising — Imperium", group: "Dragons Rising — Imperium", wave: 4 },
  { id: "rapton", name: "Rapton", power: "🏹 Dragon hunter / weapons", era: "Dragons Rising — Imperium", group: "Dragons Rising — Imperium", wave: 4 },
  { id: "dr-larow", name: "Dr. LaRow", power: "🧬 Technology / dragon-energy science", era: "Dragons Rising — Imperium", group: "Dragons Rising — Imperium", wave: 4 },
  { id: "jordana", name: "Jordana", power: "🔮 Magic + technology; later associated with Rox", era: "Dragons Rising — Imperium", group: "Dragons Rising — Imperium", wave: 4 },
  { id: "emperor-levo", name: "Emperor Levo", power: "💥 Shockwave", era: "Dragons Rising — Imperium", group: "Dragons Rising — Imperium", wave: 4 },
  { id: "zeatrix-2", name: "Zeatrix", power: "💥 Shockwave", era: "Dragons Rising — Imperium", group: "Dragons Rising — Imperium", wave: 4 },
  { id: "percival", name: "Percival", power: "🤖 Imperium technology", era: "Dragons Rising — Imperium", group: "Dragons Rising — Imperium", wave: 4 },
  { id: "frohicky", name: "Frohicky", power: "🐸 Agility / no element", era: "Dragons Rising — Imperium", group: "Crossroads / allies", wave: 4 },
  { id: "kreel", name: "Kreel", power: "⚔️ Scavenger combat", era: "Dragons Rising — Imperium", group: "Crossroads / allies", wave: 4 },
  { id: "lobbo", name: "Lobbo", power: "🤖 Robot abilities", era: "Dragons Rising — Imperium", group: "Crossroads / allies", wave: 4 },
  { id: "euphrasia-3", name: "Euphrasia", power: "🌪️ Wind", era: "Dragons Rising — Imperium", group: "Crossroads / allies", wave: 4 },
  { id: "arrakore", name: "Arrakore", power: "🧞 Wish Magic", era: "Dragons Rising — Imperium", group: "Crossroads / allies", wave: 4 },
  { id: "dorama", name: "Dorama", power: "🎭 Technology / performance weapons", era: "Dragons Rising — Imperium", group: "Crossroads / allies", wave: 4 },
  { id: "geo-3", name: "Geo", power: "🔗 Fusion", era: "Dragons Rising — Imperium", group: "Crossroads / allies", wave: 4 },
  { id: "bonzle", name: "Bonzle", power: "✨ Living spell / Magic", era: "Dragons Rising — Imperium", group: "Crossroads / allies", wave: 4 },
  { id: "fritz", name: "Fritz", power: "⚔️ Combat", era: "Dragons Rising — Imperium", group: "Crossroads / allies", wave: 4 },
  { id: "spitz", name: "Spitz", power: "⚔️ Combat", era: "Dragons Rising — Imperium", group: "Crossroads / allies", wave: 4 },
  { id: "nokt", name: "Nokt", power: "💪 Brute Force", era: "Forbidden Five", group: "Forbidden Five", wave: 4 },
  { id: "rox", name: "Rox", power: "😱 Fear", era: "Forbidden Five", group: "Forbidden Five", wave: 4 },
  { id: "zarkt", name: "Zarkt", power: "🍀❌ Misfortune", era: "Forbidden Five", group: "Forbidden Five", wave: 4 },
  { id: "drix", name: "Drix", power: "🦠 Swarm", era: "Forbidden Five", group: "Forbidden Five", wave: 4 },
  { id: "kur", name: "Kur", power: "☠️ Decay", era: "Forbidden Five", group: "Forbidden Five", wave: 4 },
  { id: "egalt", name: "Egalt", power: "🐉🌀 Spinjitzu / Rising Dragon Technique", era: "Dragon Masters", group: "Dragon Masters", wave: 4 },
  { id: "rontu", name: "Rontu", power: "🐉🌀 Spinjitzu / Rising Dragon Technique", era: "Dragon Masters", group: "Dragon Masters", wave: 4 },
  { id: "riyu-2", name: "Riyu", power: "⚡🐉 Dragon Energy", era: "Dragon Masters", group: "Major Dragons", wave: 4 },
  { id: "jiro", name: "Jiro", power: "🐉 Dragon Energy", era: "Dragon Masters", group: "Major Dragons", wave: 4 },
  { id: "heatwave", name: "Heatwave", power: "🔥🐉 Heat / Fire", era: "Dragon Masters", group: "Major Dragons", wave: 4 },
  { id: "zanth", name: "Zanth", power: "🐉 Dragon abilities", era: "Dragon Masters", group: "Major Dragons", wave: 4 },
  { id: "thunderfang", name: "Thunderfang", power: "🌩️☯️ Chaos / Shatter power", era: "Dragon Masters", group: "Major Dragons", wave: 4 },
  { id: "arc-dragon-of-focus", name: "Arc Dragon of Focus", power: "🎯🐉 Focus", era: "Dragon Masters", group: "Major Dragons", wave: 4 },
  { id: "firstbourne-2", name: "Firstbourne", power: "🐉 Primordial Dragon power", era: "Dragon Masters", group: "Major Dragons", wave: 4 },
  { id: "stormbringer-2", name: "Stormbringer", power: "⚡ Lightning", era: "Dragon Masters", group: "Major Dragons", wave: 4 },
  { id: "boreal-2", name: "Boreal", power: "❄️ Ice", era: "Dragon Masters", group: "Major Dragons", wave: 4 },
  { id: "grief-bringer-2", name: "Grief-Bringer", power: "💀 Undead Dragon", era: "Dragon Masters", group: "Major Dragons", wave: 4 },
  { id: "chompy-2", name: "Chompy", power: "🔥 Fire/Dragon power", era: "Dragon Masters", group: "Major Dragons", wave: 4 },
  { id: "zippy-2", name: "Zippy", power: "🐉 Dragon abilities", era: "Dragon Masters", group: "Major Dragons", wave: 4 },
];

export const getExpandedCatalogWave = (wave: RosterImplementationWave) =>
  EXPANDED_CHARACTER_CATALOG.filter((entry) => entry.wave === wave);

export const findExpandedCatalogEntry = (id: string) =>
  EXPANDED_CHARACTER_CATALOG.find((entry) => entry.id === id);

export const getExpandedCatalogByEra = (era: string) =>
  EXPANDED_CHARACTER_CATALOG.filter((entry) => entry.era === era);
